const API_KEY = "96be30eda92847a2b5edd3f3a907e3bd";

const ACTIONS = {
  ADD_NEWS_TO_FAVORITE: "ADD_NEWS_TO_FAVORITE",
  REMOVE_NEWS_FROM_FAVORITE: "REMOVE_NEWS_FROM_FAVORITE",
  GET_NEWS_FROM: "GET_NEWS_FROM"
};

const INITIAL_STATE = {
  news: [],
  sideNews: [],
  favoriteNews: [],
}

export { API_KEY, ACTIONS, INITIAL_STATE };
